version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
services:
  web:
    image: nginx
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST
    networks:
    - back
    - lb_web
    ports:
    - "80:80"
  app:
    image: shaunakdas2020/discourse-indie
    volumes:
      - ./data/assets:/usr/src/app/public/assets
      - ./data/uploads:/usr/src/app/public/uploads
      - ./data/backups:/usr/src/app/public/backups
    links:
      - postgres
      - redis
    env_file:
      - ./env
    environment:
      - DISCOURSE_HOSTNAME="connectrial.tk"
    networks:
    - back
  sidekiq:
    image: shaunakdas2020/discourse-indie
    command: bundle exec sidekiq -q critical -q default -q low -v
    links:
      - postgres
      - redis
    env_file:
      - ./env
    environment:
      - DISCOURSE_HOSTNAME="connectrial.tk"
    volumes_from:
      - app
    networks:
    - back
  postgres:
    image: postgres:9.4.8
    env_file:
      - ./env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
    - back
  redis:
    image: redis:3
    networks:
    - back
